apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: NodePort
  selector:
    app: website_app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website_app
spec:
  selector:
    matchLabels:
      app: website_app
  replicas: 2
  template:
    metadata:
      labels:
        app: website_app
    spec:
      containers:
       —name: website-container
          image: megmahajan/devopscap2
          ports:
           —containerPort: 80
